apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload
  namespace: default
spec:
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      labels:
        app: workload
    spec:
      containers:
      - name: workload
        image: gcr.io/alf-testing/workload:0.1.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 30m
            memory: 1G
          requests:
            cpu: 30m
            memory: 1G
