apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-spot
  namespace: default
spec:
  selector:
    matchLabels:
      app: workload-spot
  template:
    metadata:
      labels:
        app: workload-spot
    spec:
      tolerations:
      - key: spot
        operator: Equal
        value: "true"
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spot
                operator: In
                values:
                - "true"
      containers:
      - name: workload
        image: gcr.io/alf-testing/workload:0.1.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 30m
            memory: 1G
          requests:
            cpu: 30m
            memory: 1G
